### ISSUE TITLE
Importieren eines Spielfeldes

### ISSUE THREAD

**Issue by shyim** [wnklmnn/GameOfLife#2]

**Comment by wnklmnn** [comment]
Wollen wir nur das Spielfeld importieren oder auch die Einstellungen?
Und wie wollen wir die Datei aufbauen wenn wir andere Einstellungen auch
noch importieren wollen?

**Comment by shyim** [comment]
Wir können die gerne auch Exportieren. Ich dachte an ein Format wie Excel, wo nach jedem Wert ein Semikolon kommt
